### ISSUE TITLE
Wireless Module did not respond

### ISSUE THREAD

**Issue by stokes776** [ncd-io/node-red-enterprise-sensors#1]
Under what situations does the 'Wireless module did not respond' generate?

Ive got a gateway, that when I deploy the flows, ill get a spurt of data from the Xbee, but then it throws the error and dies.

![image](https://github.com/ncd-io/node-red-enterprise-sensors/assets/50416033/28e9e0bf-a69b-43fb-ad8d-a39b0f05d485)

**Comment by stokes776** [comment]
This is repeatable as well, I can repeatedly deploy the flows, get some data, then it stops.

Then I deploy the flows again, get a few more transmissions, then it stops.

**Comment by stokes776** [comment]
It seems to be something specific with 0.1.5.
When I revert to 0.1.4, the issue goes away.

**Comment by io-Jacob** [comment]
The only time you should run into this is when the wireless module does not respond to a Serial Address query which we recently added to help recover lost communications.

Is the gateway node outputting it's serial address when it changes modes? You would see this in a msg with the topic modem_mac. This error only pops up when the mode changes (Ready, Configuring, Connecting..., and Failed to Connect are the modes for this node) and the device is non-responsive to the AT command to read its serial address.

The mode changes when the config mode toggle is clicked (button left of node), the serial port connects, the serial port disconnects, and when node-red first loads there is a five second delay while the serial port connects where it will say connecting.....

Could you email me the flow you're using when you run into this? Specifically I'm curious if there are duplicate of the same ncd-config-gateway serial port in use.

Additionally if you can send any error logs you're seeing I can take a look at those.

I'll take a look and see what changes were made between 0.1.4 and 0.1.5 that might cause or exacerbate an issue like this.

**Comment by stokes776** [comment]
This no longer seems to be an issue!
